# Generated by Django 3.2.11 on 2024-11-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_establecimiento_puntoexpedicion_timbrado_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timbrado',
            name='fin_vigencia',
            field=models.DateField(verbose_name='Fin Vigencia'),
        ),
        migrations.AlterField(
            model_name='timbrado',
            name='inicio_vigencia',
            field=models.DateField(verbose_name='Inicio Vigencia'),
        ),
    ]
