# Generated by Django 3.2.11 on 2023-11-06 14:17

from django.db import migrations
from django.core.management import call_command


def load_data(apps, schema_editor):
    call_command('loaddata', 'apps/finance/fixtures/initial_pais_data.json')
    call_command('loaddata', 'apps/finance/fixtures/initial_departamento_data.json')
    call_command('loaddata', 'apps/finance/fixtures/initial_distrito_data.json')
    call_command('loaddata', 'apps/finance/fixtures/initial_localidad_data.json')
    call_command('loaddata', 'apps/finance/fixtures/initial_banco_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
