# Generated by Django 3.2.11 on 2023-10-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='abreviatura',
            field=models.CharField(max_length=10, unique=True, verbose_name='Abreviatura'),
        ),
    ]
