# Generated by Django 3.2.11 on 2024-10-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20231106_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='abreviatura',
            field=models.CharField(max_length=200, unique=True, verbose_name='Abreviatura'),
        ),
    ]
