# Generated by Django 3.2.11 on 2022-04-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_tipoimpuesto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoimpuesto',
            options={},
        ),
    ]
