# Generated by Django 3.2.11 on 2022-04-02 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_tipoimpuesto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='tipoimpuesto',
            options={'verbose_name': 'Tipo de impuesto', 'verbose_name_plural': 'Tipos de impuestos'},
        ),
    ]
