# Generated by Django 3.2.11 on 2022-04-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20220402_1842'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banco',
            table='bancos',
        ),
        migrations.AlterModelTable(
            name='cuenta',
            table='cuentas',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='departamentos',
        ),
        migrations.AlterModelTable(
            name='distrito',
            table='distritos',
        ),
        migrations.AlterModelTable(
            name='localidad',
            table='localidades',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='paises',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='personas',
        ),
        migrations.AlterModelTable(
            name='tipoimpuesto',
            table='tipos_impuestos',
        ),
    ]
