# Generated by Django 3.2.11 on 2022-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('dimensionHa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dimension Ha')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicacion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
