# Generated by Django 3.2.11 on 2022-03-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='descripcion',
            field=models.CharField(max_length=200, unique=True, verbose_name='Descripción'),
        ),
    ]
