# Generated by Django 3.2.11 on 2023-11-06 16:41

from django.db import migrations
from django.core.management import call_command


def load_data(apps, schema_editor):
    call_command('loaddata', 'apps/farming/fixtures/initial_tipoactividadagricola_data.json')
    call_command('loaddata', 'apps/farming/fixtures/initial_tipomaquinariaagricola_data.json')
    call_command('loaddata', 'apps/farming/fixtures/initial_finca_data.json')
    call_command('loaddata', 'apps/farming/fixtures/initial_calificacionagricola_data.json')
    call_command('loaddata', 'apps/farming/fixtures/initial_maquinariaagricola_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
