# Generated by Django 3.2.11 on 2022-04-02 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_auto_20220401_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acopiocalificacion',
            options={'verbose_name': 'Calificación de acopio', 'verbose_name_plural': 'Calificaciones de acopios'},
        ),
        migrations.AlterModelOptions(
            name='actividadagricola',
            options={'verbose_name': 'Actividad agricola', 'verbose_name_plural': 'Actividades agricolas'},
        ),
        migrations.AlterModelOptions(
            name='calificacionagricola',
            options={'verbose_name': 'Calificación agrícola', 'verbose_name_plural': 'Calificaciones agrícolas'},
        ),
        migrations.AlterModelOptions(
            name='cierrezafra',
            options={'verbose_name': 'Cierre de zafra', 'verbose_name_plural': 'Cierres de zafras'},
        ),
        migrations.AlterModelOptions(
            name='liquidacionagricola',
            options={'verbose_name': 'Liquidación agricola', 'verbose_name_plural': 'Liquidaciones agricolas'},
        ),
        migrations.AlterModelOptions(
            name='maquinariaagricola',
            options={'verbose_name': 'Maquinaria agrícola', 'verbose_name_plural': 'Maquinarias agrícolas'},
        ),
        migrations.AlterModelOptions(
            name='planactividadzafra',
            options={'verbose_name': 'Plan de actividad por zafra', 'verbose_name_plural': 'Plan de actividades por zafras'},
        ),
        migrations.AlterModelOptions(
            name='tipoactividadagricola',
            options={'verbose_name': 'Tipo de actividad agrícola', 'verbose_name_plural': 'Tipos de actividades agrícolas'},
        ),
        migrations.AlterModelOptions(
            name='tipomaquinariaagricola',
            options={'verbose_name': 'Tipo de maquinaria agrícola', 'verbose_name_plural': 'Tipos de maquinarias agrícolas'},
        ),
    ]
