# Generated by Django 3.2.11 on 2022-04-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0004_auto_20220402_1842'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acopio',
            table='acopios',
        ),
        migrations.AlterModelTable(
            name='acopiocalificacion',
            table='acopios_calificaciones',
        ),
        migrations.AlterModelTable(
            name='acopiodetalle',
            table='acopios_detalles',
        ),
        migrations.AlterModelTable(
            name='actividadagricola',
            table='actividades_agricolas',
        ),
        migrations.AlterModelTable(
            name='actividadagricolaitemdetalle',
            table='actividades_agricolas_items_detalles',
        ),
        migrations.AlterModelTable(
            name='actividadagricolamaquinariadetalle',
            table='actividades_agricolas_maquinarias_detalles',
        ),
        migrations.AlterModelTable(
            name='calificacionagricola',
            table='calificaciones_agricolas',
        ),
        migrations.AlterModelTable(
            name='cierrezafra',
            table='',
        ),
        migrations.AlterModelTable(
            name='cierrezafradetalle',
            table='cierres_zafras_detalles',
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='contratos',
        ),
        migrations.AlterModelTable(
            name='finca',
            table='fincas',
        ),
        migrations.AlterModelTable(
            name='liquidacionagricola',
            table='liquidaciones_agricolas',
        ),
        migrations.AlterModelTable(
            name='liquidacionagricoladetalle',
            table='liquidaciones_agricolas_detalles',
        ),
        migrations.AlterModelTable(
            name='lote',
            table='lotes',
        ),
        migrations.AlterModelTable(
            name='maquinariaagricola',
            table='maquinarias_agricolas',
        ),
        migrations.AlterModelTable(
            name='planactividadzafra',
            table='planes_actividades_zafras',
        ),
        migrations.AlterModelTable(
            name='planactividadzafradetalle',
            table='planes_actividades_zafras_detalles',
        ),
        migrations.AlterModelTable(
            name='tipoactividadagricola',
            table='tipos_actividades_agricolas',
        ),
        migrations.AlterModelTable(
            name='tipomaquinariaagricola',
            table='tipos_maquinarias_agricolas',
        ),
        migrations.AlterModelTable(
            name='zafra',
            table='zafras',
        ),
    ]
