from apps.finance import autocomplete, views
from django.conf.urls import url
from django.urls import path

urlpatterns = [
    path("impuesto/<int:pk>/delete/", views.TipoImpuestoDeleteView.as_view(), name="impuesto_delete"),
    path("impuesto/<int:pk>/update/", views.TipoImpuestoUpdateView.as_view(), name="impuesto_update"),
    path("impuesto/add", views.TipoImpuestoCreateView.as_view(), name="impuesto_create"),
    path("impuesto/",  views.TipoImpuestoListView.as_view(), name="impuesto_list"),
    path("cuenta/<int:pk>/delete/", views.CuentaDeleteView.as_view(), name="cuenta_delete"),
    path("cuenta/<int:pk>/update/", views.CuentaUpdateView.as_view(), name="cuenta_update"),
    path("cuenta/add", views.CuentaCreateView.as_view(), name="cuenta_create"),
    path("cuenta/",  views.CuentaListView.as_view(), name="cuenta_list"),
    path("pais/<int:pk>/delete/", views.PaisDeleteView.as_view(), name="pais_delete"),
    path("pais/<int:pk>/update/", views.PaisUpdateView.as_view(), name="pais_update"),
    path("pais/add", views.PaisCreateView.as_view(), name="pais_create"),
    path("pais/",  views.PaisListView.as_view(), name="pais_list"),
    path("departamento/<int:pk>/delete/", views.DepartamentoDeleteView.as_view(), name="departamento_delete"),
    path("departamento/<int:pk>/update/", views.DepartamentoUpdateView.as_view(), name="departamento_update"),
    path("departamento/add", views.DepartamentoCreateView.as_view(), name="departamento_create"),
    path("departamento/",  views.DepartamentoListView.as_view(), name="departamento_list"),
    path("distrito/<int:pk>/delete/", views.DistritoDeleteView.as_view(), name="distrito_delete"),
    path("distrito/<int:pk>/update/", views.DistritoUpdateView.as_view(), name="distrito_update"),
    path("distrito/add", views.DistritoCreateView.as_view(), name="distrito_create"),
    path("distrito/",  views.DistritoListView.as_view(), name="distrito_list"),
    path("localidad/<int:pk>/delete/", views.LocalidadDeleteView.as_view(), name="localidad_delete"),
    path("localidad/<int:pk>/update/", views.LocalidadUpdateView.as_view(), name="localidad_update"),
    path("localidad/add", views.LocalidadCreateView.as_view(), name="localidad_create"),
    path("localidad/",  views.LocalidadListView.as_view(), name="localidad_list"),
    path("persona/<int:pk>/delete/", views.PersonaDeleteView.as_view(), name="persona_delete"),
    path("persona/<int:pk>/update/", views.PersonaUpdateView.as_view(), name="persona_update"),
    path("persona/add", views.PersonaCreateView.as_view(), name="persona_create"),
    path("persona/",  views.PersonaListView.as_view(), name="persona_list"),
    url(r'^proveedor-autocomplete/$', autocomplete.ProveedorAutocomplete.as_view(), name='proveedor_autocomplete',),
    url(r'^cliente-autocomplete/$', autocomplete.ClienteAutocomplete.as_view(), name='cliente_autocomplete',),
    url(r'^empleado-autocomplete/$', autocomplete.EmpleadoAutocomplete.as_view(), name='empleado_autocomplete',),
    path("banco/<int:pk>/delete/", views.BancoDeleteView.as_view(), name="banco_delete"),
    path("banco/<int:pk>/update/", views.BancoUpdateView.as_view(), name="banco_update"),
    path("banco/add", views.BancoCreateView.as_view(), name="banco_create"),
    path("banco/",  views.BancoListView.as_view(), name="banco_list"),
]
