from apps.finance import views
from django.urls import path

from .views import (BancoCreateView, BancoDeleteView, BancoListView,
                    BancoUpdateView, CuentaCreateView, CuentaDeleteView,
                    CuentaListView, CuentaUpdateView, DepartamentoCreateView,
                    DepartamentoDeleteView, DepartamentoListView,
                    DepartamentoUpdateView, DistritoCreateView,
                    DistritoDeleteView, DistritoListView, DistritoUpdateView,
                    LocalidadCreateView, LocalidadDeleteView,
                    LocalidadListView, LocalidadUpdateView, PaisCreateView,
                    PaisDeleteView, PaisListView, PaisUpdateView,
                    PersonaCreateView, PersonaDeleteView, PersonaListView,
                    PersonaUpdateView, TipoImpuestoCreateView,
                    TipoImpuestoDeleteView, TipoImpuestoListView,
                    TipoImpuestoUpdateView)

urlpatterns = [
    path("impuesto/<int:pk>/delete/", TipoImpuestoDeleteView.as_view(), name="impuesto_delete"),
    path("impuesto/<int:pk>/update/", TipoImpuestoUpdateView.as_view(), name="impuesto_update"),
    path("impuesto/add", TipoImpuestoCreateView.as_view(), name="impuesto_create"),
    path("impuesto/",  TipoImpuestoListView.as_view(), name="impuesto_list"),
    path("cuenta/<int:pk>/delete/", CuentaDeleteView.as_view(), name="cuenta_delete"),
    path("cuenta/<int:pk>/update/", CuentaUpdateView.as_view(), name="cuenta_update"),
    path("cuenta/add", CuentaCreateView.as_view(), name="cuenta_create"),
    path("cuenta/",  CuentaListView.as_view(), name="cuenta_list"),
    path("pais/<int:pk>/delete/", PaisDeleteView.as_view(), name="pais_delete"),
    path("pais/<int:pk>/update/", PaisUpdateView.as_view(), name="pais_update"),
    path("pais/add", PaisCreateView.as_view(), name="pais_create"),
    path("pais/",  PaisListView.as_view(), name="pais_list"),
    path("departamento/<int:pk>/delete/", DepartamentoDeleteView.as_view(), name="departamento_delete"),
    path("departamento/<int:pk>/update/", DepartamentoUpdateView.as_view(), name="departamento_update"),
    path("departamento/add", DepartamentoCreateView.as_view(), name="departamento_create"),
    path("departamento/",  DepartamentoListView.as_view(), name="departamento_list"),
    path("distrito/<int:pk>/delete/", DistritoDeleteView.as_view(), name="distrito_delete"),
    path("distrito/<int:pk>/update/", DistritoUpdateView.as_view(), name="distrito_update"),
    path("distrito/add", DistritoCreateView.as_view(), name="distrito_create"),
    path("distrito/",  DistritoListView.as_view(), name="distrito_list"),
    path("localidad/<int:pk>/delete/", LocalidadDeleteView.as_view(), name="localidad_delete"),
    path("localidad/<int:pk>/update/", LocalidadUpdateView.as_view(), name="localidad_update"),
    path("localidad/add", LocalidadCreateView.as_view(), name="localidad_create"),
    path("localidad/",  LocalidadListView.as_view(), name="localidad_list"),
    path("persona/<int:pk>/delete/", PersonaDeleteView.as_view(), name="persona_delete"),
    path("persona/<int:pk>/update/", PersonaUpdateView.as_view(), name="persona_update"),
    path("persona/add", PersonaCreateView.as_view(), name="persona_create"),
    path("persona/",  PersonaListView.as_view(), name="persona_list"),
    path("banco/<int:pk>/delete/", BancoDeleteView.as_view(), name="banco_delete"),
    path("banco/<int:pk>/update/", BancoUpdateView.as_view(), name="banco_update"),
    path("banco/add", BancoCreateView.as_view(), name="banco_create"),
    path("banco/",  BancoListView.as_view(), name="banco_list"),
]
