# Generated by Django 3.2.11 on 2022-07-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(verbose_name='Fecha')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('es_planta_acopiadora', models.BooleanField(default=False, verbose_name='Es Planta Acopiadora?')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('ultimo_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ult. Costo')),
                ('es_activo', models.BooleanField(verbose_name='Activo?')),
                ('codigo_barra', models.CharField(max_length=20, verbose_name='Cód Barra')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo de item',
                'verbose_name_plural': 'Tipos de items',
            },
        ),
        migrations.CreateModel(
            name='ItemMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('fecha_documento', models.DateField(verbose_name='Fecha Documento')),
                ('secuencia_origen', models.IntegerField()),
                ('detalle_secuencia_origen', models.IntegerField()),
                ('es_vigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('tipo_movimiento', models.CharField(choices=[('CM', 'COMPRAS'), ('VT', 'VENTAS'), ('A+', 'AJUSTES STOCK +'), ('A-', 'AJUSTES STOCK -'), ('AC', 'ACOPIOS'), ('AA', 'ACTIVIDADES AGRICOLAS'), ('DC', 'DEVOLUCIONES DE COMPRAS'), ('DV', 'DEVOLUCIONES DE VENTAS')], max_length=50, verbose_name='Tipo Mov.')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.tipoimpuesto', verbose_name='Tipo Imp.'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoitem', verbose_name='Tipo Item'),
        ),
        migrations.CreateModel(
            name='AjusteStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('ajuste_stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ajustestock')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito'),
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.persona', verbose_name='Empleado'),
        ),
    ]
