# Generated by Django 3.2.11 on 2022-03-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_tipoimpuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('es_planta_acopiadora', models.BooleanField(default=False, verbose_name='Es Planta Acopiadora?')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('ultimo_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ult. Costo')),
                ('es_activo', models.BooleanField(verbose_name='Activo?')),
                ('codigo_barra', models.CharField(max_length=20, verbose_name='Cód Barra')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.categoria', verbose_name='Categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.marca', verbose_name='Marca')),
                ('tipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.tipoimpuesto', verbose_name='Tipo Imp.')),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoitem', verbose_name='Tipo Item')),
            ],
        ),
    ]
