# Generated by Django 3.2.11 on 2022-04-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_tipoimpuesto'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(verbose_name='Fecha')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.persona', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('fecha_documento', models.DateField(verbose_name='Fecha Documento')),
                ('secuencia_origen', models.IntegerField()),
                ('detalle_secuencia_origen', models.IntegerField()),
                ('es_vigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('tipo_movimiento', models.CharField(choices=[('CM', 'COMPRAS'), ('VT', 'VENTAS'), ('A+', 'AJUSTES STOCK +'), ('A-', 'AJUSTES STOCK -'), ('AC', 'ACOPIOS'), ('AA', 'ACTIVIDADES AGRICOLAS'), ('DC', 'DEVOLUCIONES DE COMPRAS'), ('DV', 'DEVOLUCIONES DE VENTAS')], max_length=50, verbose_name='Tipo Mov.')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='AjusteStockDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('ajuste_stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ajustestock')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
    ]
