# Generated by Django 3.2.11 on 2022-04-02 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ajustestock_ajustestockdetalle_itemmovimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoitem',
            options={'verbose_name': 'Tipo de item', 'verbose_name_plural': 'Tipos de items'},
        ),
    ]
