# Generated by Django 3.2.11 on 2023-11-06 14:54

from django.db import migrations
from django.core.management import call_command


def load_data(apps, schema_editor):
    call_command('loaddata', 'apps/inventory/fixtures/initial_tipoitem_data.json')
    call_command('loaddata', 'apps/inventory/fixtures/initial_unidadmedida_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20231030_1021'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
