# Generated by Django 3.2.11 on 2022-04-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_tipoitem_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ajustestock',
            table='ajustes_stock',
        ),
        migrations.AlterModelTable(
            name='ajustestockdetalle',
            table='ajustes_stock_detalles',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='deposito',
            table='depositos',
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
        migrations.AlterModelTable(
            name='itemmovimiento',
            table='items_movimientos',
        ),
        migrations.AlterModelTable(
            name='marca',
            table='marcas',
        ),
        migrations.AlterModelTable(
            name='tipoitem',
            table='tipos_items',
        ),
    ]
