# Generated by Django 3.2.11 on 2022-03-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('finance', '0002_tipoimpuesto'),
        ('supplies', '0003_auto_20220306_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(verbose_name='Fecha Documento')),
                ('es_vigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(verbose_name='Fecha Documento')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('es_vigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.persona', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.pedidocompra')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Descuento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.ordencompra')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='pedido_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.pedidocompra', verbose_name='Pedido Compra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.persona', verbose_name='Proveedor'),
        ),
    ]
