# Generated by Django 3.2.11 on 2022-04-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ajustestock_ajustestockdetalle_itemmovimiento'),
        ('finance', '0002_tipoimpuesto'),
        ('supplies', '0004_auto_20220306_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoRecibida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(verbose_name='Fecha')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('es_credito', models.BooleanField(default=False, verbose_name='Es Crédito?')),
                ('es_vigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.compra', verbose_name='Compra')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.cuenta', verbose_name='Cuenta')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.persona', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='NotaDebitoRecibida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(verbose_name='Fecha Documento')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('es_credito', models.BooleanField(default=False, verbose_name='Es Crédito?')),
                ('es_vigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.compra', verbose_name='Compra')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.cuenta', verbose_name='Cuenta')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.persona', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='NotaDebitoRecibidaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio/Aumento')),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('nota_debito_recibida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.notadebitorecibida')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoRecibidaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo/Descuento')),
                ('es_devolucion', models.BooleanField(default=False, verbose_name='Es Devolución?')),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('nota_credito_recibida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplies.notacreditorecibida')),
            ],
        ),
    ]
