# Generated by Django 3.2.11 on 2022-04-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_auto_20220402_1842'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compra',
            table='compras',
        ),
        migrations.AlterModelTable(
            name='compradetalle',
            table='compras_detalles',
        ),
        migrations.AlterModelTable(
            name='cuotacompra',
            table='cuotas_compras',
        ),
        migrations.AlterModelTable(
            name='notacreditorecibida',
            table='notas_creditos_recibidas',
        ),
        migrations.AlterModelTable(
            name='notacreditorecibidadetalle',
            table='notas_creditos_recibidas_detalles',
        ),
        migrations.AlterModelTable(
            name='notadebitorecibida',
            table='notas_debitos_recibidas',
        ),
        migrations.AlterModelTable(
            name='notadebitorecibidadetalle',
            table='notas_debitos_recibidas_detalles',
        ),
        migrations.AlterModelTable(
            name='ordencompra',
            table='ordenes_compras',
        ),
        migrations.AlterModelTable(
            name='ordencompradetalle',
            table='ordenes_compras_detalles',
        ),
        migrations.AlterModelTable(
            name='pedidocompra',
            table='pedidos_compras',
        ),
        migrations.AlterModelTable(
            name='pedidocompradetalle',
            table='pedidos_compras_detalles',
        ),
    ]
